name: Android CI

on:
  workflow_dispatch:

jobs:
  android_test:
     name: Running Android Tests
     runs-on: macos-13
     continue-on-error: true
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
           api-level: 26
           target: default
           arch: x86_64
           profile: Nexus 4
           emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
           script: |
            adb wait-for-device
            adb shell input keyevent 82
